### ISSUE TITLE
顶栏可以单独滑动，这样会导致日期和下面的item不对齐

### ISSUE THREAD

**Issue by DearZack** [Kelin-Hong/ScrollablePanel#1]
ScrollablePanel类中其他的RecyclerView都有initRecyclerView(RecyclerView),只有headerRecyclerView没有init，问题应该出在这里。

PinFirstItemRecyclerView这个类是精华，一开始我想不通你的第一项时怎么处理的，看了源码才知道原来可以这样，学习了，赞！

**Comment by Kelin-Hong** [comment]
谢谢提醒，测试的时候没有注意，现在这个问题已经fix了 😁
