### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by panyz** [Kelin-Hong/ScrollablePanel#15]
你好，如果我想在此基础上再增加几级表头，请问有什么思路可以做出来呢

**Comment by Kelin-Hong** [comment]
你好，表头是另外加的，目前控件不支持添加表头，你只能clone下来去修改代码，表头是另外的一个RecyclerView，你需要新添加一个RecyclerView，并在滑动的时候带动其他RecyclerView,主要是滑动事件的传递带动，不是很难的
